var a;
a = 'angular';
a = 10;
a = true;
var b = 'Hello';
var ch1 = b.endsWith('o');
console.log(ch1);
var c;
c = 'welcome';
var ch2 = c.concat(' Raju');
console.log(ch2);
var ch3 = ch2.endsWith('u');
console.log(ch3);
